---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: headlamp
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.38.0
  url: oci://ghcr.io/home-operations/charts-mirror/headlamp
---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  chartRef:
    kind: OCIRepository
    name: headlamp
  dependsOn: []
  interval: 15m
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"
    fullnameOverride: headlamp
    initContainers:
      - command:
          - /bin/sh
          - -c
          - |
            cp /tmp/kubeconfig $KUBECONFIG && chown :101 $KUBECONFIG
            kubectl config set-cluster main --server=https://kubernetes.default.svc --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            kubectl config set-credentials main --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            kubectl config set-context main --cluster=main --user=main
        env:
          - name: KUBECONFIG
            value: /home/headlamp/.config/Headlamp/kubeconfigs/config
        image: docker.io/rancher/shell:v0.6.0
        name: create-kubeconfig
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs
            name: kubeconfig
          - mountPath: /tmp/kubeconfig
            name: storage-auth
            readOnly: true
            subPath: config
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.5.0@sha256:05c3df203b2ff82e09e944e31cd16ab66429f37df7566ba0d47285add7c78c5a
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    config:
      extraArgs:
        - -cache-enabled
        - -kubeconfig=/home/headlamp/.config/Headlamp/kubeconfigs/config
      inCluster: false
      pluginsDir: /build/plugins
    serviceAccount:
      create: false
      name: headlamp
    clusterRoleBinding:
      create: false
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
      - name: kubeconfig
        emptyDir: {}
      - name: storage-auth
        secret:
          defaultMode: 416
          secretName: headlamp-storage-auth
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
      - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs/config
        name: kubeconfig
        readOnly: true
        subPath: config
