apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:xOC0t+E9b28=,iv:usaV9dSkzpxJzqZDDinKJanxcyspd3+92Jca1ofLFIk=,tag:VPqiMr+2Wjm2P/rk3s+T/Q==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:a6PoF6IGVsc7eTag26F/arfJ1GOThv8aRKLrhoQ9jYzNs//O6wnvwCp0SvCwaHXI8Ga/0TYZq7qvxcjTgeSHiQ==,iv:gY9u8a8JoXAgreM1EyvCzAyF5bQ+85zvnx5XQths5ro=,tag:UyBdlgpDNP10cKjcn8Un4w==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:DQFdBZBCZoOReAN641jrU1nVwiJCZ/snxl4VVaWc9PNaEHerOESdREcbT98OlhzDzg==,iv:X9bmuQVRpUy/VpTaWZKFdFBKIF/Pr1CLbGIRFn6RKDA=,tag:Z971jguTfntDGtsT5yFsYw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:D+RRv+8XN4Gx6ViRTkeAwmFQdfc=,iv:6WsM9c1q3QrbQCgC/MFdCSuasobRB9Z/DnoBgcpkom4=,tag:RriySr6rihfF9i4iLZ5liQ==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbDdHM3hKSzdEY3VlYW45
            ZGVyV3NXQm15cEt2Y0hOYllyd2NaZC9GeXhJCjhRMHZJWGZLejZ6bVBjQVJqMHFk
            VjJ5ZjA2bnl2bFFxOFcyZFFsNW8rM00KLS0tIEFxYi9YZEZ5S3UxQW9iTUlDc1V0
            elJ0dnJXalFDK095S0tPRWdwdURUZjAKlKu0DHKGUQXngvp0yq7snAsnz0WMumeZ
            PKcFowo4H0ilPO+W2da8ltJ8YYoZpmzdUyIH5gW0V3+vW2msT5NuuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T19:07:54Z"
    mac: ENC[AES256_GCM,data:GIqQlxKNBhbye62YLWZ7qjOfzeiqa3+sFaYBfQWJQolnVhTK7387YTbmjJ1Ppy9b5hC+hSsAy/Yr4bC5h+g/28xUQOwK+wOJi3h8VLPkl5XX9X+FD0HV/Jya6VIB2g6Nt82YvMnjStRWy8rwbhU1e5VJ8j+pcQF1+s/qhxP0+cw=,iv:Mgsxmv7SWFmDxzgEwYPagQ5Hhiq64sFt3ALRmJDUQJ8=,tag:KDHK0EN6HZ85GNm8rBZdTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
