apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:xOC0t+E9b28=,iv:usaV9dSkzpxJzqZDDinKJanxcyspd3+92Jca1ofLFIk=,tag:VPqiMr+2Wjm2P/rk3s+T/Q==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:a6PoF6IGVsc7eTag26F/arfJ1GOThv8aRKLrhoQ9jYzNs//O6wnvwCp0SvCwaHXI8Ga/0TYZq7qvxcjTgeSHiQ==,iv:gY9u8a8JoXAgreM1EyvCzAyF5bQ+85zvnx5XQths5ro=,tag:UyBdlgpDNP10cKjcn8Un4w==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:DQFdBZBCZoOReAN641jrU1nVwiJCZ/snxl4VVaWc9PNaEHerOESdREcbT98OlhzDzg==,iv:X9bmuQVRpUy/VpTaWZKFdFBKIF/Pr1CLbGIRFn6RKDA=,tag:Z971jguTfntDGtsT5yFsYw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:06MFmd3gE+SA2Fy7G84nuXnfv1U=,iv:kKeCbBFQW1+9rITiVIsnQsLqJEge08TuxbUuUzL3kwE=,tag:RCR4yTVCbr4jWE+mSbeOgA==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbDdHM3hKSzdEY3VlYW45
            ZGVyV3NXQm15cEt2Y0hOYllyd2NaZC9GeXhJCjhRMHZJWGZLejZ6bVBjQVJqMHFk
            VjJ5ZjA2bnl2bFFxOFcyZFFsNW8rM00KLS0tIEFxYi9YZEZ5S3UxQW9iTUlDc1V0
            elJ0dnJXalFDK095S0tPRWdwdURUZjAKlKu0DHKGUQXngvp0yq7snAsnz0WMumeZ
            PKcFowo4H0ilPO+W2da8ltJ8YYoZpmzdUyIH5gW0V3+vW2msT5NuuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T19:19:15Z"
    mac: ENC[AES256_GCM,data:yRHTPgU+BtEAtpsDiHIK6KmbW3zRV+MJvEDou22f1uK9sCD3u9Xb4uz9KcCsi43TbSntWcFTAWLuBhhTEA5qUFNrY9AWU1IY80OtjQrQCLgU9JTYyUMyBGn5yGlgEqdQNfNxoqywC2WqtxSLPPMssj2sEtDErfIaTxIJ7mtsUVU=,iv:Z7l+eoZi9fpLJ5xMyaBKg0os38CR6yctB0iF7om0t6E=,tag:6ARvGymC+fY+OhgPEE8nfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
