---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: miscellaneous
spec:
  groups:
    - name: dockerhub
      rules:
        - alert: BootstrapRateLimitRisk
          annotations:
            summary: Kubernetes cluster at risk of being rate limited by dockerhub on bootstrap
          expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          for: 15m
          labels:
            severity: critical
    - name: oom
      rules:
        - alert: OOMKilled
          annotations:
            summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
          expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          labels:
            severity: critical
    - name: temperature
      rules:
        - alert: ChipTemperatureHigh
          annotations:
            summary: Chip {{$labels.chip}}/{{$labels.sensor}} on {{$labels.instance}} has a temperature higher than 70Â°C
          expr: node_hwmon_temp_celsius > 70
          for: 15m
          labels:
            severity: critical
    - name: wireguard
      rules:
        - alert: WireguardTunnelDown
          annotations:
            summary: Wireguard tunnel is down for more than 10 minutes now
          expr: time() - wireguard_latest_handshake_seconds{public_key="EdmzcHAwnIn5Uv/SRDKBnwBUZIVxZ2MUnT7Ps/zFLHw="} > 600
          for: 10m
          labels:
            severity: critical
