apiVersion: v1
kind: Secret
metadata:
    name: vikunja
stringData:
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:s0N32APYQw==,iv:sP2uzbq+0ge3T0yuInwC79wteh7g9KQi1N6n8oPBN0U=,tag:m/zCLMtE4hvibh5t7thiSQ==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:JJ+53sQwtDbGrEB0hWb4FUm148hLilkr,iv:jfr5vVMTA71XlvZIj7c5hghxCfzzUMUVgEV6S3s8mG8=,tag:1rRfMJon/vlVLxmKMe2fOw==,type:str]
    VIKUNJA_DATABASE_HOST: ENC[AES256_GCM,data:tB6hHWlGls1YQYbpm4MVtA6a81zX8nHZfymq+QrjsZ5qWa2mGSXxSHx6T4um,iv:x2dTU4NIFlCAP2vCjPnlxgutGLI0N2wwkLTSfJ6+2vA=,tag:DC3OcTW5bdnMDxvbLZNCsQ==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:DPyuob1ceg==,iv:OXeNurn5YjZKfFeOC54QTcVDGsGg0LYGahaE2bZYJMk=,tag:JQ2/SWjMxJJtFElgQ171xA==,type:str]
    VIKUNJA_MAILER_HOST: ENC[AES256_GCM,data:qQjuztuikzdUa/PIx5cZugRWMEV/pLNkdZwdnGzyZu6DawBm,iv:fLGeFA+LrOWHUu6a9IfQBVbpdOCFoWHguqtJvUAMc9Q=,tag:7SUTivE/aAQ6xOSj37W7Bw==,type:str]
    VIKUNJA_MAILER_PORT: ENC[AES256_GCM,data:WfA=,iv:hBjm7AsJXzUHwDVGLACmKa6JH8YO3glINMUK14EFE1s=,tag:LUoAASFOHW2G+Rubi8EhPQ==,type:str]
    VIKUNJA_MAILER_FROMEMAIL: ENC[AES256_GCM,data:0DiMAQtnScGpRkFqyYr++VNlnIBXFRdxY1ZIF1xnjphZ7jJXcdmhCPOiqE1fUGA=,iv:xaMQzS1XPI2pWoG5ZGbYy+1fg8M/2qQnWSxALPgJz8k=,tag:DcZCr/rROL45jQd/Fl2iWg==,type:str]
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:vjf2pLmHuEXZwOPGjBCFdK0wQvLmN3eGe6HXWlHSjxUT8TD6VCoUmBw9jJIWsBHUk7sYVtYYaMU9mkAOW4QzUP12m24/yDs9BrGusB9fv4Y+jwi9BfqDvw==,iv:GgdNztOsKMB/VGXzCa7KBlZIXVYmVU6kGpv0dkVCL7c=,tag:QT8gqQVLVQ1U6k9rtDsCjQ==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZE9ML2pvazgxTWpBaEl2
            bWlSMWdJajlyRTFFNUhzSHVoOEpyNlBTM2g0Cks1ZmpUc2JFVENxRStDU3JPbGVG
            VkxLVGlqN3dCNVZlOVdXdnFlNFNrNUkKLS0tIE1yMFlZNjZCc0lzVVNSSEJjK3NF
            dEhZTTRNTzFqNWFaY3R6aGMxT0FvR1EKcebphCwdNO7MbTsME6j2slNXVvci9qAg
            2TApMzDBpsmJTlWeiW/GMWQkeJc6C1UCYa335csIdQ0PR9fXkx+vYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:38:18Z"
    mac: ENC[AES256_GCM,data:bR8bKrrd+na9NiD5sloVst2fn6VWEiJiJovlAl0vePw9r3QGBALDLas3N/sASUZz0aRC1bv9/yVYI4Fd9zCtj6NfhzPlL5xTMUc87J7ITz5F4aUFUu84YRONKoFnJxydnaUxZpEbMR2Pk2wJ1bTxABRDljBe+9NvenS02mkmdww=,iv:NqvNnO5C1gj3khpPgliggja+yjhL7IiIeVPMusUGnbs=,tag:2eJceubfVAF7VfuHJD9uWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-init-db
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:DKU1VYlSqA==,iv:7JJnl0p0SN9j0zmpAtJGz9z3f4a3pt9TH/40npJb7kI=,tag:pVTZSdWHmxAWSbd/mZ6SsQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:WZitazBrn6lvEdwFfsU6e3rFb5tVFvSUo8R4aN+acn27idEFPU+94g==,iv:oWDKu1C7qBd1l3VPAEfNOwW0bRRNHtd+CxwkU6vwoNs=,tag:AvxIyJIjLrfARA7GKgELKw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:UJQk4oJLhA==,iv:HqbcC5TTBL14ZEDP0/2qErwNH09ilxUTCFk4SWlmPu4=,tag:pVx6ZU+qAp0poSpbBx9TPg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:4PPmbfNcbhNQNqo7L/WM8PKqqhBdIS6+,iv:jTJxHZUtjkgFr4s8IsX1zOcael9EZ3BlGabZ7gHelZE=,tag:6WT/Q2qo+jYwMQzuG8JLFg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:vFSXamGRlWIc4udZNRBAZ8tlG875we8l6sly0BWkqc44,iv:wxaJCFV65xGBLVa5iMAA+lzGliG0cK5vkC1EYDuc9DE=,tag:vXB9IGt1LeGrNLuXpzv73w==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZE9ML2pvazgxTWpBaEl2
            bWlSMWdJajlyRTFFNUhzSHVoOEpyNlBTM2g0Cks1ZmpUc2JFVENxRStDU3JPbGVG
            VkxLVGlqN3dCNVZlOVdXdnFlNFNrNUkKLS0tIE1yMFlZNjZCc0lzVVNSSEJjK3NF
            dEhZTTRNTzFqNWFaY3R6aGMxT0FvR1EKcebphCwdNO7MbTsME6j2slNXVvci9qAg
            2TApMzDBpsmJTlWeiW/GMWQkeJc6C1UCYa335csIdQ0PR9fXkx+vYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:38:18Z"
    mac: ENC[AES256_GCM,data:bR8bKrrd+na9NiD5sloVst2fn6VWEiJiJovlAl0vePw9r3QGBALDLas3N/sASUZz0aRC1bv9/yVYI4Fd9zCtj6NfhzPlL5xTMUc87J7ITz5F4aUFUu84YRONKoFnJxydnaUxZpEbMR2Pk2wJ1bTxABRDljBe+9NvenS02mkmdww=,iv:NqvNnO5C1gj3khpPgliggja+yjhL7IiIeVPMusUGnbs=,tag:2eJceubfVAF7VfuHJD9uWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-config
stringData:
    config.yaml: ENC[AES256_GCM,data:+FLD/qHx1bWi1BHHzQbPB4QB7aQVwiYnVxMMmLK2eAA4+x9Ep8AJYiXDIFFh8j9hTq6J7VWXGXeEGXbA+LcveAy0uLl/xnhiEy0vcU+xP4LLhMHKWkeW2sE2v8C4he1rXEDiX66f73VWMtl6+n3z4p3LavWuuH/bwsZ7/m6maAlenI2F3vucXNFKss3/JgUioOO6Ar3UhTOmkgPcBG5FWhTcFWwurTlytuu7IKsYj7n0cxkJBATfeVPhlv2Hm25cyrNxdVuIWw9xd1elRp+5+JidBb8BjytKxlraoK8t3CZsoBFtnMcGinezCfVhHO7kiyk/rzUWP2hlBKwmLZQoaybReMI6AejucY0TNr5Le8dKnG6+tD7+YB3HOyal+9acx+XHEIn9CFKp4gcFeO2Fzp4SZmIv8HxgQ/gEVxM34N41i89/MDnVdsYA0Rf7,iv:JRTXnWpDa0ugSU71gywozH53GEg1x2U34loz+bwYjD4=,tag:bmTyyQOoBJzi1x+ptOjJgg==,type:str]
sops:
    age:
        - recipient: age1u79ltfzz5k79ddwgv59r76p2532xnaehzz7vggttctudr6gdkvhq33edn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZE9ML2pvazgxTWpBaEl2
            bWlSMWdJajlyRTFFNUhzSHVoOEpyNlBTM2g0Cks1ZmpUc2JFVENxRStDU3JPbGVG
            VkxLVGlqN3dCNVZlOVdXdnFlNFNrNUkKLS0tIE1yMFlZNjZCc0lzVVNSSEJjK3NF
            dEhZTTRNTzFqNWFaY3R6aGMxT0FvR1EKcebphCwdNO7MbTsME6j2slNXVvci9qAg
            2TApMzDBpsmJTlWeiW/GMWQkeJc6C1UCYa335csIdQ0PR9fXkx+vYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:38:18Z"
    mac: ENC[AES256_GCM,data:bR8bKrrd+na9NiD5sloVst2fn6VWEiJiJovlAl0vePw9r3QGBALDLas3N/sASUZz0aRC1bv9/yVYI4Fd9zCtj6NfhzPlL5xTMUc87J7ITz5F4aUFUu84YRONKoFnJxydnaUxZpEbMR2Pk2wJ1bTxABRDljBe+9NvenS02mkmdww=,iv:NqvNnO5C1gj3khpPgliggja+yjhL7IiIeVPMusUGnbs=,tag:2eJceubfVAF7VfuHJD9uWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
