---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: community.general
    version: 12.2.0
  - name: community.sops
    version: 2.2.7
  - name: kubernetes.core
    version: 6.2.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.6.2
  - name: githubixx.ansible_role_wireguard
    src: https://github.com/githubixx/ansible-role-wireguard
    version: 18.3.0
  - name: geerlingguy.nfs
    src: https://github.com/geerlingguy/ansible-role-nfs
    version: 2.1.1
