---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: community.general
    version: 10.1.0
  - name: community.sops
    version: 2.0.1
  - name: kubernetes.core
    version: 5.0.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.4.4
  - name: githubixx.ansible_role_wireguard
    src: https://github.com/githubixx/ansible-role-wireguard
    version: 17.1.0
  - name: geerlingguy.nfs
    src: https://github.com/geerlingguy/ansible-role-nfs
    version: 2.1.0
